#!/bin/sh

#"获取当前脚本路径"
basepath=$(cd `dirname $0`; pwd)
cd ${basepath}

podName=""
updatefile=""

files=$(ls)
for filename in $files
do
    if [[ $filename =~ "podspec" ]]; then
        podName=$filename
    fi
    if [[ $filename = "update.txt" ]]; then
        updatefile=$filename
    fi
done

if [ -n "$podName" ]; then
    echo "文件名称: $podName"

    version=$(sed -n 5p $podName | sed 's/\(.*\)"\(.*\)"\(.*\)/\2/g')
    sdkName=$(sed -n 4p $podName | sed 's/\(.*\)"\(.*\)"\(.*\)/\2/g')
    echo "当前版本号: $version"
    echo "sdk名称:$sdkName"

    echo "添加文件"
    git add *

    if [ -n "$updatefile" ]; then
        filecontent=$(cat $updatefile)
        git commit -m $filecontent
    else 
        git commit -m "$version"
    fi

    git push origin master

    git tag "$version"
    git push --tags

    echo "提交sdk"
    pod trunk push $podName --allow-warnings --verbose

else
    echo "没有获取到podspec"
fi
